
# DataBase
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.137/xy_unmannedhotel120?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xyzh2018
  # thymeleaf
  thymeleaf:
    cache: false
  # redis
  redis:
    host: 192.168.1.138
    port: 6379
    database: 7
  # application name
  application:
    name: device-collect-management
# port
server:
  port: 8089
# mapper location
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml