# DataBase
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
  datasource:
    hikari:
      max-lifetime: 120000
      maximum-pool-size: 50
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.137/xy_unmannedhotel120?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    url: jdbc:mysql://120.92.33.104/xy_unmanedhotel_1.4?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://8.129.15.73/ViansTest_suqinglin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    #    password: xyzh2018
    password: 81BACAD41DDF1
  # thymeleaf
  thymeleaf:
    cache: false
  # redis
  redis:
    host: localhost
    port: 6379
    database: 3
#  redis:
#    host: 120.92.114.123
#    port: 6379
#    database: 2
#    password: xyzh2019
  # application name
  application:
    name: device-collect-management
# port
server:
  port: 8089
# mapper location
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.vians.admin.mapper: debug
system:
  url: http://admin.szvians.cn:8087
  physicUser: 18580250664
  physicPsw: 123456

